apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    purpose: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability